name: Check Duplicate Issues

on:
  issues:
    types: [opened]

jobs:
  check-duplicate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Find duplicate issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_TITLE=$(echo "${{ github.event.issue.title }}" | tr '[:upper:]' '[:lower:]')
        DUPLICATE=$(gh issue list --state open --search "$ISSUE_TITLE" --json number,title --jq '.[] | select(.number != ${{ github.event.issue.number }})')
        
        if [[ -n "$DUPLICATE" ]]; then
          DUPLICATE_NUMBER=$(echo "$DUPLICATE" | jq -r '.number')
          
          # Close the duplicate issue
          gh issue close ${{ github.event.issue.number }} --comment "This issue is a duplicate of #$DUPLICATE_NUMBER. Please refer to the original issue for updates."

          echo "Duplicate issue found and closed."
        else
          echo "No duplicate issue found."
        fi
