name: Download and Release Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 requests
      - name: Run the download and release script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service_account.json
          echo "$TELEGRAM_BOT_TOKEN" > TELEGRAM_BOT_TOKEN
          echo "$TELEGRAM_CHAT_ID" > TELEGRAM_CHAT_ID
          python download_and_release.py
