name: Monitor External Repository Commits

on:
  schedule:
    # Runs every 30 minutes. Adjust the schedule as needed.
    - cron: '*/30 * * * *'
  workflow_dispatch:
  
jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios dotenv

      - name: Monitor External Repo Commits
        run: node ./scripts/monitorExternalRepo.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Make sure this token has necessary access
